// Code generated by hertz generator.

package hello

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	hello "hertz-example/biz/model/hertz/hello"
)

// Method1 .
// @router /hello [GET]
func Method1(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hello.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(hello.HelloResp)

	//处理逻辑
	resp.RespBody = "hello," + req.Name

	c.JSON(consts.StatusOK, resp)
}

// Method2 .
// @router /other [POST]
func Method2(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hello.OtherReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(hello.OtherResp)

	// 增加的逻辑
	resp.Resp = "Other method: " + req.Other

	c.JSON(consts.StatusOK, resp)
}
