// Code generated by hertz generator.

package hello

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	hello "hertz-example/biz/model/hertz/hello"
)

// Method3 .
// @router /new [GET]
func Method3(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hello.OtherReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(hello.OtherResp)

	c.JSON(consts.StatusOK, resp)
}
